name: freecodecamp
description: freecodecamp.org app.
publish_to: none
version: 5.0.2+50002
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  algolia_helper_flutter: ^1.0.0
  audio_service: ^0.18.13
  # NOTE: Versions 1.5.0 and above support iOS 13+ only
  auth0_flutter: <=1.4.1
  cached_network_image: ^3.3.1
  curl_logger_dio_interceptor: ^1.0.0 # NOTE: Do we still want this?
  device_info_plus: ^9.1.2 # TODO: upgrade after migrating to FLutter 3.19
  dio: ^5.4.3+1
  firebase_analytics: ^11.3.3
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.3
  firebase_remote_config: ^5.1.3
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_heatmap_calendar: ^1.0.4
  flutter_highlight: ^0.7.0
  flutter_hooks: ^0.20.5
  flutter_html: 3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  flutter_inappwebview: ^6.1.0 # TODO: upgrade after migrating to FLutter 3.19
  flutter_local_notifications: ^17.1.0
  flutter_localizations:
    sdk: flutter
  flutter_scroll_shadow: ^1.2.4
  flutter_secure_storage: ^9.0.0
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  html: ^0.15.4
  infinite_scroll_pagination: ^4.0.0
  jiffy: ^6.2.1 # TODO: upgrade after migrating to FLutter 3.19
  just_audio: ^0.10.0
  path: ^1.8.3 # TODO: upgrade after migrating to FLutter 3.19
  path_provider: ^2.1.3
  phone_ide: ^1.3.0
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.2.0-beta-1 # NOTE: Do we still want this?
  quick_actions: ^1.0.7
  share_plus: ^7.2.2 # TODO: upgrade after migrating to FLutter 3.19
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  # TODO: Replace with sqflite methods as below package isn't actively maintained
  sqflite_migration_service: ^2.0.0-nullsafety.1
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  ua_client_hints: ^1.4.1
  upgrader: ^10.2.0
  url_launcher: ^6.2.6
  web_socket_channel: ^2.4.0
  youtube_player_iframe: ^5.1.2 # 2.3.0 last working with fullscreen
dev_dependencies:
  build_runner: ^2.4.9
  dependency_validator: ^3.2.3
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  sqflite_common_ffi: ^2.3.3
  stacked_generator: ^1.6.0

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/sql/
    - assets/test_data/news_post.json
    - assets/test_data/news_feed.json
    - assets/database/bookmarked-article.db
    - assets/learn/
