name: freecodecamp
description: freecodecamp.org app.
publish_to: none
version: 2.0.5+20005
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter_font_awesome_web_names:
    git:
      url: https://github.com/Mythar/flutter_font_awesome_web_names
      ref: master
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_html: ^2.2.1
  flutter_lints: ^1.0.4
  flutter_slidable: ^0.6.0
  flip_card: ^0.5.0
  flutter_skeleton: ^0.1.0+1
  flutter_swiper: ^1.1.6
  algolia: ^1.0.1
  podcast_search: ^0.5.0
  just_audio: ^0.9.7
  http: ^0.13.3
  logger: ^1.1.0
  path_provider: ^2.0.3
  sqflite: ^2.0.0+4
  stacked: ^2.2.5
  stacked_services: ^0.8.13
  ui_helper: ^1.1.0
  url_launcher: ^6.0.10
  webview_flutter: ^2.0.12
  sqflite_migration_service: ^2.0.0-nullsafety.1
  json_serializable: ^4.1.4
  dio: ^4.0.0
  just_audio_background: ^0.0.1-beta.1
  hexcolor: ^2.0.5
  flutter_syntax_view:
    git:
      url: https://github.com/Sembauke/flutter_syntax_view
      ref: master
  jiffy: ^5.0.0
  share: ^2.0.4
  flutter_svg: ^0.23.0+1
  shared_preferences: ^2.0.7
  font_awesome_flutter: ^9.1.0
  html: ^0.15.0
  uuid: ^3.0.5
  fk_user_agent: ^2.0.1
  flutter_hooks: ^0.18.0
  readmore: ^2.1.0
  flutter_local_notifications: ^9.0.3
  image_picker: ^0.8.4+4
  youtube_player_iframe: ^2.2.2
  web_socket_channel: ^2.1.0
dev_dependencies:
  build_runner: ^2.1.2
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.4.8
dependency_overrides:
  meta: 1.3.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/sql/
    - assets/database/cards-jwasham.db
    - assets/database/bookmarked-article.db
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
