name: freecodecamp
description: freecodecamp.org app.
publish_to: none
version: 4.1.8+40108
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_html: 3.0.0-beta.2
  algolia: ^1.1.2 # TODO: Replace package with official one
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  stacked: ^3.4.2
  stacked_services: ^1.5.0
  url_launcher: ^6.2.5
  # TODO: Replace with sqflite methods as below package isn't actively maintained
  sqflite_migration_service: ^2.0.0-nullsafety.1
  dio: ^5.4.2+1
  phone_ide: ^1.2.3
  jiffy: ^6.2.1 # TODO: upgrade after migrating to FLutter 3.19
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.4.0
  html: ^0.15.4
  fk_user_agent: ^2.0.1 # TODO: replace with ua_client_hints package
  flutter_hooks: ^0.20.5
  # NOTE: After migrating to flutter 3.19, check for build warnings
  flutter_local_notifications: ^17.0.0
  youtube_player_iframe: ^4.0.4
  infinite_scroll_pagination: ^4.0.0
  web_socket_channel: ^2.4.0 # TODO: upgrade after migrating to FLutter 3.19
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.0.0
  photo_view: ^0.14.0
  share_plus: ^7.2.2 # TODO: upgrade after migrating to FLutter 3.19
  # NOTE: Do we still want these?
  pretty_dio_logger: ^1.2.0-beta-1
  curl_logger_dio_interceptor: ^1.0.0
  flutter_heatmap_calendar: ^1.0.4
  intl: ^0.18.1 # TODO: replace with jiffy
  path: ^1.8.3 # TODO: upgrade after migrating to FLutter 3.19
  audio_service: ^0.18.12
  device_info_plus: ^9.1.2 # TODO: upgrade after migrating to FLutter 3.19
  # NOTE: Versions 1.5.0 and above support iOS 13+ only
  auth0_flutter: <=1.4.1
  upgrader: ^10.0.1
  quick_actions: ^1.0.7
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.9
  flutter_custom_tabs: ^1.0.4
  flutter_scroll_shadow: ^1.2.4
  firebase_crashlytics: ^3.4.18
  flutter_highlight: ^0.7.0
  flutter_inappwebview: ^5.8.0 # TODO: upgrade after migrating to FLutter 3.19
  flutter_html_table: ^3.0.0-beta.2
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.1.2
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  stacked_generator: ^1.5.1 # TODO: upgrade after migrating to FLutter 3.19
  flutter_launcher_icons: ^0.13.1
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.3.2+1
  mockito: ^5.3.2
  http: ^0.13.6 # TODO: upgrade package when algolia is replaced

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/sql/
    - assets/test_data/news_post.json
    - assets/test_data/news_feed.json
    - assets/database/bookmarked-article.db
    - assets/learn/
