name: freecodecamp
description: freecodecamp.org app.
publish_to: none
version: 3.3.2+30302
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_html: ^2.2.1
  algolia: ^1.0.1
  just_audio: ^0.9.7
  http: ^0.13.3
  path_provider: ^2.0.3
  sqflite: ^2.0.0+4
  stacked: ^3.1.0
  stacked_services: ^1.0.0
  url_launcher: ^6.0.10
  sqflite_migration_service: ^2.0.0-nullsafety.1
  dio: ^4.0.0
  phone_ide: ^1.0.2
  jiffy: ^6.0.0
  shared_preferences: ^2.0.7
  font_awesome_flutter: ^10.0.0
  html: ^0.15.0
  fk_user_agent: ^2.0.1
  flutter_hooks: ^0.18.0
  flutter_local_notifications: ^9.0.3
  youtube_player_iframe: ^4.0.0
  infinite_scroll_pagination: ^3.1.0
  web_socket_channel: ^2.1.0
  cached_network_image: ^3.2.0
  flutter_secure_storage: ^8.0.0
  photo_view: ^0.14.0
  share_plus: ^6.3.0
  pretty_dio_logger: ^1.2.0-beta-1
  curl_logger_dio_interceptor: ^0.0.3
  flutter_heatmap_calendar: ^1.0.4
  intl: ^0.18.0
  path: ^1.8.1
  audio_service: ^0.18.4
  device_info_plus: ^6.0.0
  auth0_flutter: ^1.0.1
  upgrader: ^4.6.1
  quick_actions: ^1.0.1
  firebase_core: ^2.4.0
  firebase_analytics: ^10.1.0
  flutter_custom_tabs: ^1.0.4
  flutter_scroll_shadow: ^1.1.0
  firebase_crashlytics: ^3.0.17
  flutter_highlight: ^0.7.0
  flutter_inappwebview: ^5.7.2+3
dev_dependencies:
  build_runner: ^2.1.2
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  stacked_generator: ^1.0.0
  flutter_launcher_icons: ^0.11.0
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.2.1+1
  mockito: ^5.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/sql/
    - assets/test_data/news_post.json
    - assets/test_data/news_feed.json
    - assets/database/bookmarked-article.db
    - assets/learn/
