name: freecodecamp
description: freecodecamp.org app.
publish_to: none
version: 7.2.0+71200
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  algolia_helper_flutter: 1.2.1
  audio_service: 0.18.18
  auth0_flutter: 1.9.0
  cached_network_image: 3.4.1
  collection: 1.19.1
  device_info_plus: 11.3.0
  dio: 5.8.0+1
  firebase_analytics: 11.4.5
  firebase_core: 3.13.0
  firebase_crashlytics: 4.3.5
  firebase_remote_config: 5.4.3
  flutter:
    sdk: flutter
  flutter_custom_tabs: 2.4.0
  flutter_dotenv: 5.2.1
  flutter_heatmap_calendar: 1.0.5
  flutter_highlight: 0.7.0
  flutter_hooks: 0.21.2
  flutter_html: 3.0.0
  flutter_html_table: 3.0.0
  flutter_inappwebview: 6.1.5
  flutter_local_notifications: 19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_scroll_shadow: 1.2.6
  flutter_secure_storage: 9.2.4
  flutter_svg: 2.1.0
  focus_detector: 2.0.1
  graphql: 5.2.0
  html: 0.15.5+1
  infinite_scroll_pagination: 5.0.0
  jiffy: 6.3.2
  just_audio: 0.10.4
  path: 1.9.1
  path_provider: 2.1.5
  phone_ide: 2.0.1
  photo_view: 0.15.0
  pretty_dio_logger: 1.4.0
  quick_actions: 1.1.0
  share_plus: 10.1.4 # NOTE: v11 has breaking changes
  shared_preferences: 2.5.3 # TODO: update deprecated code
  sqflite: 2.4.2
  stacked: 3.4.3
  stacked_services: 1.6.0
  timezone: 0.10.1
  ua_client_hints: 1.4.1
  upgrader: 11.3.1
  url_launcher: 6.3.2
  web_socket_channel: 3.0.3
  youtube_player_iframe: 5.2.2
dev_dependencies:
  build_runner: 2.4.13
  dependency_validator: 3.2.3
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: 0.14.3
  flutter_lints: 5.0.0
  flutter_native_splash: 2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.4 # NOTE: 5.4.6+ is blocked by stacked_generator
  stacked_generator: 1.6.1

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Hack
      fonts:
        - asset: assets/fonts/Hack-Regular.ttf
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
    - assets/sql/
    - assets/test_data/news_post.json
    - assets/test_data/news_feed.json
    - assets/database/bookmarked-article.db
    - assets/learn/
    - assets/test_runner/dist/
    - assets/test_runner/babel/
