name: freecodecamp
description: freecodecamp.org app.
publish_to: none
version: 3.0.1+30001
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter_font_awesome_web_names:
    git:
      url: https://github.com/Mythar/flutter_font_awesome_web_names
      ref: master
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_html: ^2.2.1
  algolia: ^1.0.1
  just_audio: ^0.9.7
  http: ^0.13.3
  logger: ^1.1.0
  path_provider: ^2.0.3
  sqflite: ^2.0.0+4
  stacked: ^3.0.0
  stacked_services: ^0.9.0
  url_launcher: ^6.0.10
  sqflite_migration_service: ^2.0.0-nullsafety.1
  json_serializable: ^6.0.0
  dio: ^4.0.0
  hexcolor: ^3.0.0
  flutter_syntax_view_fcc:
    git:
      url: https://github.com/Sembauke/flutter_syntax_view_fcc
      ref: master
  flutter_code_editor:
    git:
      url: https://github.com/freeCodeCamp/PhoneIDE
      ref: main
  jiffy: ^5.0.0
  flutter_svg: ^0.23.0+1
  shared_preferences: ^2.0.7
  font_awesome_flutter: ^10.0.0
  html: ^0.15.0
  fk_user_agent: ^2.0.1
  flutter_hooks: ^0.18.0
  flutter_local_notifications: ^9.0.3
  image_picker: ^0.8.4+4
  youtube_player_iframe: ^2.2.2
  infinite_scroll_pagination: ^3.1.0
  web_socket_channel: ^2.1.0
  webview_flutter: ^2.8.0
  cached_network_image: ^3.2.0
  webview_cookie_manager: ^2.0.6
  flutter_secure_storage: ^7.0.1
  photo_view: ^0.14.0
  share_plus: ^5.0.0
  flutter_highlight:
    git:
      url: https://github.com/sembauke/highlight.dart
      ref: master
      path: ./flutter_highlight
  pretty_dio_logger: ^1.2.0-beta-1
  curl_logger_dio_interceptor: ^0.0.3
  flutter_heatmap_calendar: ^1.0.4
  intl: ^0.17.0
  path: ^1.8.1
  audio_service: ^0.18.4
  device_info_plus: ^4.0.1
  upgrader: ^4.6.1
  quick_actions: ^1.0.1
dev_dependencies:
  build_runner: ^2.1.2
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.8.0
  flutter_launcher_icons: ^0.11.0
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-logo.png"

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/sql/
    - assets/test_data/news_post.json
    - assets/test_data/news_feed.json
    - assets/database/bookmarked-article.db
    - assets/learn/
