name: Build and Deploy API

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
        site_tlds: [dev, org]

    steps:
      - name: Checkout source code
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          cd mobile-api
          npm ci --no-audit --no-progress --no-optional --no-shrinkwrap

      - name: Build site
        env:
          NODE_ENV: production
        run: npm run build:api

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Docker login to Azure Container Registry
        uses: azure/docker-login@81744f9799e7eaa418697cb168452a2882ae844a # tag=v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Docker Images
        run: |
          cd mobile-api
          tagname=$(git rev-parse --short HEAD)-$(date +%Y%m%d)-$(date +%H%M)
          docker build . \
          --tag ${{ secrets.ACR_NAME }}.azurecr.io/${{ matrix.site_tlds }}/mobile-api:$tagname \
          --tag ${{ secrets.ACR_NAME }}.azurecr.io/${{ matrix.site_tlds }}/mobile-api:latest \
          --file Dockerfile
          docker push --all-tags ${{ secrets.ACR_NAME }}.azurecr.io/${{ matrix.site_tlds }}/mobile-api
